import { StyleSheet } from "react-native";

export const contactStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: "#121212" },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingTop: 6,
    paddingBottom: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#1A1A1A",
  },
  headerTitle: { color: "#FFFFFF", fontSize: 22, fontWeight: "800" },
  headerIconButton: {
    width: 50,
    height: 50,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.03)",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#2A2A2A",
  },
  headerIconButtonActive: {
    backgroundColor: "rgba(0,191,166,0.2)",
    borderColor: "#00BFA6",
  },

  container: { padding: 16, paddingBottom: 24 },

  card: {
    backgroundColor: "#1A1A1A",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#2A2A2A",
    padding: 14,
    marginBottom: 18,
  },
  cardIntro: {
    color: "#DADADA",
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 10,
  },
  caption: { color: "#9A9A9A", fontSize: 12, marginBottom: 14 },

  label: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "700",
    marginBottom: 6,
    marginTop: 10,
  },
  input: {
    backgroundColor: "#232323",
    color: "#FFFFFF",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#2A2A2A",
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  inputError: { borderColor: "#FF4D6D" },
  textarea: { minHeight: 140, paddingTop: 12 },

  counterRow: {
    marginTop: 6,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  hintText: { color: "#9A9A9A", fontSize: 12 },
  counterText: { color: "#B5B5B5", fontSize: 12 },

  submitBtn: {
    height: 48,
    borderRadius: 999,
    backgroundColor: "#171717",
    borderWidth: 1,
    borderColor: "#2A2A2A",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
  },
  submitBtnPressed: { backgroundColor: "#1E1E1E" },
  submitBtnDisabled: { opacity: 0.6 },
  submitText: { color: "#FFFFFF", fontWeight: "700" },

  group: {
    backgroundColor: "#141414",
    borderRadius: 14,
    padding: 12,
    marginBottom: 18,
    borderWidth: 1,
    borderColor: "#1E1E1E",
  },
  groupTitle: { color: "#BEBEBE", fontSize: 13, marginBottom: 10, marginLeft: 4 },
  submitWrap: { width: "70%", alignSelf: "center" },
  submitGradient: { padding: 2, borderRadius: 10 },

  successPopup: {
    position: "absolute",
    bottom: 40,
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#1A1A1A",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#00BFA6",
    paddingVertical: 12,
    paddingHorizontal: 18,
    shadowColor: "#000",
    shadowOpacity: 0.3,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 8,
  },
  successText: { color: "#FFFFFF", fontSize: 15, fontWeight: "600" },

  overlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.45)",
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
    zIndex: 999,
  },
  overlayCard: {
    width: "100%",
    maxWidth: 420,
    backgroundColor: "#1A1A1A",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#2A2A2A",
    padding: 16,
    alignItems: "center",
  },
  overlayTitle: { color: "#FFFFFF", fontSize: 18, fontWeight: "800", marginBottom: 4, textAlign: "center" },
  overlayMsg: { color: "#B5B5B5", fontSize: 14, lineHeight: 20, textAlign: "center" },

  modalOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.7)",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 99,
  },

  modalCard: {
    backgroundColor: "#1A1A1A",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#2A2A2A",
    width: "80%",
    paddingVertical: 28,
    paddingHorizontal: 20,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOpacity: 0.4,
    shadowRadius: 20,
    elevation: 10,
  },

  modalTitle: { color: "#FFFFFF", fontSize: 18, fontWeight: "800", marginBottom: 8, textAlign: "center" },
  modalSubtitle: { color: "#B5B5B5", fontSize: 14, lineHeight: 20, textAlign: "center", marginHorizontal: 8 },

  errorText: { color: "#FF4D6D", fontSize: 12, marginTop: 4 },

  // Button styles used in the component
  button: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 15,
    paddingHorizontal: 15,
    gap: 10,
  },
  buttonIcon: {
    width: 22,
    height: 22,
    resizeMode: "contain",
    marginRight: 8,
  },
  buttonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
  },
});

