import { StyleSheet } from "react-native";
import { screenHeight } from "../../ui/sharedUI";

export const mainScreenStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: "#121212" },
  content: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 16,
  },
  header: {
    width: "100%",
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#121212",
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 10,
  },
  headerMenuButton: { marginRight: -40 },
  headerLogo: { width: 40, height: 40, resizeMode: "contain" },
  tabContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignSelf: "center",
    width: "90%",
    columnGap: 20,
    marginTop: 50,
    marginBottom: 8,
  },
  tabButtonWrapper: { flex: 1, borderRadius: 10 },
  tabButton: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 16,
    borderRadius: 10,
  },
  tabButtonActive: { backgroundColor: "#1A1A1A" },
  tabButtonText: { color: "#FFFFFF", fontSize: 15, fontWeight: "600" },
  tabButtonTextActive: { color: "#00BFA6" },
  tabButtonActiveBorder: {
    borderWidth: 1,
    borderColor: "#00BFA6",
    borderRadius: 10,
  },
  button: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 15,
    paddingHorizontal: 15,
    gap: 10,
  },
  buttonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
  },
  footer: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    alignItems: "center",
  },
  footerText: { color: "#999", textAlign: "center", fontSize: 12 },
});

export const cardStyles = StyleSheet.create({
  cardShadow: {
    width: "90%",
    alignSelf: "center",
    borderRadius: 18,
    shadowColor: "#000",
    shadowOpacity: 0.35,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
    elevation: 8,
    minHeight: screenHeight * 0.55,
    overflow: "hidden",
  },
  cardInner: {
    borderRadius: 18,
    backgroundColor: "rgba(18, 18, 18, 0.8)",
    paddingTop: 16,
    paddingBottom: 24,
    paddingHorizontal: 16,
    minHeight: screenHeight * 0.55,
    overflow: "hidden",
  },
  topRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  modePill: {
    backgroundColor: "#1C1C1C",
    borderRadius: 999,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#2A2A2A",
  },
  modePillText: { color: "#D8D8D8", fontSize: 12, fontWeight: "600" },
  favoriteBtn: {
    padding: 6,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.03)",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#2A2A2A",
  },
  centerWrap: {
    flexGrow: 1,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    padding: 50,
  },
  promptText: {
    color: "#FFFFFF",
    fontSize: 18,
    lineHeight: 26,
    textAlign: "center",
    fontWeight: "600",
  },
  arrowsRow: {
    position: "absolute",
    left: 0,
    right: 0,
    top: "50%",
    marginTop: -12,
    paddingHorizontal: 16,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  circleBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#2A2A2A",
    alignItems: "center",
    justifyContent: "center",
  },
  hintPill: {
    alignSelf: "center",
    marginTop: 8,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderRadius: 999,
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#2A2A2A",
  },
  hintText: { color: "#B5B5B5", fontSize: 12 },
});

